data:
  # 原始合同数据存放目录（请将你的合同文档放入该目录，支持 docx/pdf 格式）
  raw_dir: "data/raw"
  # 预处理后的合同文本存放目录（程序会将预处理结果存入此目录）
  processed_dir: "data/processed"
  # Ground truth 文件路径：存放真实标签的 JSON 文件（格式见下文说明）
  ground_truth_file: "data/ground_truth.json"
  # 风险知识库文件路径：存放风险描述的 JSON 文件（格式见下文说明）
  risk_knowledge_file: "data/risk_knowledge.json"

model:
  # 使用的 SentenceTransformer 预训练模型名称
  sentence_transformer_model: "all-MiniLM-L6-v2"
  # 使用的基础 API 模型名称
  openai_engine: "Qwen/Qwen2.5-7B-Instruct"
  # API 密钥
  openai_api_key: "sk-uguyxxsgallvomtewqjjhylobterkeokllqgiyehnfjnfpdd"
  # DeepSeek 模型配置
  deepseek_max_tokens: 500
  deepseek_temperature: 0.3
  # MiniCPM 模型配置
  minicpm_max_tokens: 400
  minicpm_temperature: 0.2

experiment:
  # 检索模块的相似度阈值（建议在0.6-0.8之间调整）
  retrieval_threshold: 0.6
  # 调用 prompt 模块时，返回文本的最大 token 数
  prompt_max_tokens: 150
  # 调用 COT 模块时，返回文本的最大 token 数
  cot_max_tokens: 300
  # 评估时正类的标签，默认 "包含"
  evaluation_positive_label: "包含"
  # 并行处理的批次大小
  batch_size: 5
  # 模型协作阈值
  collaboration_threshold: 0.2
  # 实验结果保存目录
  results_dir: "experiments/results"
  # 实验日志保存目录
  logs_dir: "experiments/logs"

logging:
  # 日志级别：DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # 是否记录到文件
  log_to_file: true
  # 日志文件格式
  format: "[%(asctime)s] %(levelname)s: %(message)s"